FROM alpine:edge
RUN apk add --no-cache openjdk21
RUN apk --no-cache add curl
EXPOSE 8080
COPY target/users-service.jar /app/users-service.jar
WORKDIR /app
ENTRYPOINT ["java","-jar","users-service.jar"]