FROM alpine:edge
RUN apk add --no-cache openjdk21
RUN apk --no-cache add curl
EXPOSE 8080
COPY target/sales-service.jar /app/sales-service.jar
WORKDIR /app
ENTRYPOINT ["java","-jar","sales-service.jar"]