FROM alpine:edge
RUN apk add --no-cache openjdk21
RUN apk --no-cache add curl
EXPOSE 8080
COPY target/product-service.jar /app/product-service.jar
WORKDIR /app
ENTRYPOINT ["java","-jar","product-service.jar"]